AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for s3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: template-s3-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
  S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: template-s3-2
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false