AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation for lambda function and s3 bucket
Resources:
  CFNLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: cfn_lambda
      Handler: lambda/cfn_lambda.lambda_handler
      Role:
        'Fn::GetAtt':
          - CFNLambdaRole
          - Arn
      Code:
        S3Bucket: nyu-cc-pip1
        S3Key: Archive.zip
      Runtime: python3.7
      Timeout: 300
  CFNLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: cfn_lambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
      
        - PolicyName: AWSLambdaExecute
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: '*'
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - 'arn:aws:s3:::exchange-data-raw'
                  - 'arn:aws:s3:::exchange-data-raw/*'
        - PolicyName: AmazonRekognitionFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                  - "rekognition:*"
                Resource: 
                  - "*"
        - PolicyName: AmazonLexFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:DescribeAlarmsForMetric"
                  - "kms:DescribeKey"
                  - "kms:ListAliases"
                  - "lambda:GetPolicy"
                  - "lambda:ListFunctions"
                  - "lex:*"
                  - "polly:DescribeVoices"
                  - "polly:SynthesizeSpeech"
                  - "kendra:ListIndices"
                  - "iam:ListRoles"
                  - "s3:ListAllMyBuckets"
                  - "logs:DescribeLogGroups"
                  - "s3:GetBucketLocation"
                Resource: 
                  - "*"
        - PolicyName: AmazonOpenSearchServiceFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                  - "es:*"
                Resource: 
                  - "*"